### PR TITLE
Add web3/metamask-compatible personal_sign and personal_recover, fixes #18

### LINKED ISSUE #18: Trouble validating signatures from MetaMask
Hey there, thanks for the project. It's been super helpful.

What I'm trying to do is validate a signed message that I can get from MetaMask. Getting the signature is easy. Let's say I've signed the message "numa", and I get the signature `0x641a251cce30223cbcf391ecfe3aa939acc7361bbaf166dd929f940bf6589f8b3a2defc1b19c5db7f5816cc83a07a1be5a452e0387491a52e3b50c5138b7acb81c`. Here is the code that I think would work:

~~~ruby
Eth.configure { |e| e.chain_id = 1 }
message_hash = Eth::Utils.keccak256("numa")
signature = Eth::Utils.hex_to_bin("0x641a251cce30223cbcf391ecfe3aa939acc7361bbaf166dd929f940bf6589f8b3a2defc1b19c5db7f5816cc83a07a1be5a452e0387491a52e3b50c5138b7acb81c")
public_hex = Eth::OpenSsl.recover_compact(message_hash, signature)
~~~

But `public_hex` is `nil`. After debugging, I'm finding that the [`BN_cmp(x, field) >= 0`](https://github.com/se3000/ruby-eth/blob/75d5bff9138471c256c270b3fb5d3de8f65b70ad/lib/eth/open_ssl.rb#L122) flag is caught, which is why it returns nil. Unfortunately I don't really understand what this aspect of the code is doing. I'd really appreciate any help, if possible.

Thanks!

### PR DESCRIPTION
**Pull request by buhrmi**

### CODE REVIEW

**Comment by buhrmi** [comment]
This should resolve #18

**Comment by se3000** [comment]
Awesome! Thank you for spearheading this.

One thing: I've been trying to move towards accepting and returning binary data in hex. Could you switch the API to match that?

**Comment by buhrmi** [comment]
done

**Comment by buhrmi** [comment]
what's the holdup?

**Comment by se3000** [comment]
This is a side project, so it's a bit hard to find the time to give this the thought it needs.

Anyway, thanks for the contribution and for your patience. Just bumped the version and released the newest gem.

🍻

**Comment by buhrmi** [comment]
awesome. yeah I totally get it. It's an amazing gem for a side project. 

anyways, now the method signature is not in line with the rest of the API (expecting hex parameters whereas the rest of the API is still expecting binary). ah well. good enough :P

**Comment by se3000** [comment]
Thanks, happy it's getting some usage!

I'm only really moving towards hex strings. Added the [tx_data_hex configuration option](https://github.com/se3000/ruby-eth/blob/master/lib/eth.rb#L64) a few minor versions back. I'd like to get all parts of the gem using it for consistency's sake, but like I said, tight on time.

**Pull request merged**
