### PR TITLE
Replace OpenSSL With rbsecp25k1

### PR DESCRIPTION
**Pull request by etscrivner**
### Overview
This change replaces the current OpenSSL secp256k1 ECDSA with [rbsecp256k1](https://github.com/etscrivner/rbsecp256k1), a native extension gem binding to libsecp256k1. It replaces all key generation, signing, and key recovery methods with their rbsecp256k1 equivalents.

Directly using libsecp256k1 will provide performance and security benefits over the current hand-rolled OpenSSL version.

- [x] Replacing OpenSSL
  - [X] Replace OpenSSL usage with rbsecp256k1.
  - [x] Remove OpenSSL dependency and Secp256k1 module.
- [x] Clean up and refactoring
  - [x] Factor out recoverable signature functionality into a single interface.

### CODE REVIEW

**Comment by akodkod** [comment]
@etscrivner unfortunately, your solution still doesn't work for me. When I'm trying to run `rails console` I get this error and nothing else:

```
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Any ideas?

**Comment by andremedeiros** [comment]
@se3000 do you need someone to take over this PR? I'm getting an issue with OpenSSL on Mac (it pretends to be OpenSSL but it's really LibreSSL) and this PR could make my life a lot easier.

**Comment by keo** [comment]
would love to have this working!

**Comment by q9f** [comment]
If anyone wants to take over this work and rebase it on the latest version of ruby-eth, I would be happy to review and integrate it.

**Comment by q9f** [comment]
I implemented this in https://github.com/q9f/eth.rb/pull/4 and https://github.com/q9f/eth.rb/pull/24 and plan to release it as 0.5.0 soon. Thanks for your pioneering work @etscrivner 🎉

**Pull request closed without merging**
