### PR TITLE
lib: fix compatibility with libressl (macos) and openssl 1.1.1k

### PR DESCRIPTION
**Pull request by q9f**
attempt to address #47 by applying @raggi 's work at [bitcoin-ruby#311](https://github.com/lian/bitcoin-ruby/pull/311)

cc @zeptonaut - I would agree though using a proper ruby/openssl implementation should be the greater goal.

### CODE REVIEW

**Comment by q9f** [comment]
abort trap: 6 indicates issues with libssl; please confirm

**Comment by justinsoong** [comment]
@q9f i've tried using your branch to load the gem, and the abort trap is still happening (macOS, 11.6)
``` 
ruby is loading libcrypto in an unsafe way
```

**Comment by q9f** [comment]
I guess I need to get a mac then :S

**Comment by justinsoong** [comment]
@q9f this is an interesting thread: https://github.com/cl-plus-ssl/cl-plus-ssl/issues/114

**Comment by justinsoong** [comment]
@q9f it worked after i did this

```
sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1k/lib/libssl.1.1.dylib /usr/local/lib/libssl.dylib
sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1k/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.dylib
```

**Comment by justinsoong** [comment]
@q9f this might be interesting money-tree is a dep and is loading openssl in the old way also causing issues, merge is waiting though: https://github.com/GemHQ/money-tree/pull/43

**Comment by q9f** [comment]
I got myself a mac and the issue is indeed money-tree. I'm trying to reach out to them.

**Comment by wink** [comment]
I hear you guys loud and clear. money-tree hasn't been actively maintained for a while. Monkey patching OpenSSL was the only solution I had at the time to perform the proper calculations. It wasn't intended to stay in there for so many years. I'm going to chat with @q9f after Thanksgiving about maintaining it.

**Comment by justinsoong** [comment]
@wink @q9f 👍 🙏  Thank you for your efforts! Looking forward to contributing! Good news is that the MoneyTree calcs are only in two places :)

**Comment by raggi** [comment]
I'm cc'd into this due to my fixing a related library. If a maintainer/patch author would like some help solving for the local problems feel free to reach out to me with some details and I'll be happy to provide some advice.

**Comment by q9f** [comment]
> I'm cc'd into this due to my fixing a related library. If a maintainer/patch author would like some help solving for the local problems feel free to reach out to me with some details and I'll be happy to provide some advice.

Thank you for your comment. Historically, the `eth` gem inherited the openssl code from the `bitcoin` gem. I applied your patch (thank you, btw 🙏🏼) and it fixes the aforementioned issues. Now we just have the `money-tree` dependency that also has this issue. But hopefully, we'll be able to address this soon with @wink after Thanksgiving. :)

**Comment by jake** [comment]
thanks for getting this sorted! what all is left to get this released?  I'm working on a project where this would be very helpful and just wondering if it'd work in my timeline.

**Comment by q9f** [comment]
Hi Jake, just waiting for the money tree release so that I can bump the dependency.

https://github.com/GemHQ/money-tree/issues/50

**Pull request merged**
